### ISSUE TITLE
Loot Bag Adjustments

### ISSUE THREAD

**Issue by im-hyps** [MrHipsterG/Soothico#2]
Loot bags, as they stand are a way of getting trickle resources of things that you could otherwise find by exploring, losing the incentive to explore. They need to be adjusted to ensure that loot bags' contents are, for the most part, unable to be found simply by exploring.

**Comment by MrHipsterG** [comment]
Adjusted the drops for the lootbags to no longer include random vegetables and act more as cool rewards.
