### ISSUE TITLE
Corundum Recipe

### ISSUE THREAD

**Issue by im-hyps** [MrHipsterG/Soothico#5]
Currently Quark Corundum doesn't have much of a practical use aside from decoration.
Idea: The ability to grind Corundum crystals into dye.

**Comment by MrHipsterG** [comment]
Personally I think the recipe instead should instead for be stained glass.

**Comment by im-hyps** [comment]
oh shit aye i meant that

**Comment by MrHipsterG** [comment]
Added recipe for grinding corundum crystal into dyes (decided this was better after discussion)
